class RET:
    PARAMERR = '1'
    DBERR = '1'
    NODATA = '1'
    DATAERR = '1'
    DATAEXIST = '1'
    OK = '0'
    REQERR = '1'
    SESSIONERR = '1'
    THIRDERR = '1'
    MAILERR = '1'
    TIMERR = '1'
    ADMINERR = '1'
    FILERR = '1'
